name: Build and Push Multiple Containers

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Ensure secrets are accessible

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Secret Availability
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "ERROR: DOCKERHUB_USERNAME is not set or accessible!"
            exit 1
          else
            echo "DOCKERHUB_USERNAME is available!"
          fi

          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "ERROR: DOCKERHUB_TOKEN is not set or accessible!"
            exit 1
          else
            echo "DOCKERHUB_TOKEN is available!"
          fi

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || exit 1
          echo "Docker login successful!"

      - name: Build and Push Each Container
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          for dir in amazoncorretto17-al2023 ubuntu24; do
            echo "Building and pushing $dir..."
            docker build -t $DOCKERHUB_USERNAME/$dir:latest -f $dir/Dockerfile $dir/
            docker push $DOCKERHUB_USERNAME/$dir:latest
            echo "$dir image pushed successfully!"
          done
